// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: seNiaoyHbqUbSRTV4dz1rm
// Component: hhAG-0aVlGG7
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import NavigationBar from "../../NavigationBar"; // plasmic-import: 4kcPOvZyEqwE/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import ProjectCard from "../../ProjectCard"; // plasmic-import: oVPzHMtsKF-V/component
import ContactSection from "../../ContactSection"; // plasmic-import: orvYAM0G-kSD/component
import Footer from "../../Footer"; // plasmic-import: pDPGks3vTyHu/component
import { useScreenVariants as useScreenVariantsl9TsMn1DF1V } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: l9TsMn1d_f1V/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: seNiaoyHbqUbSRTV4dz1rm/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: hhAG-0aVlGG7/css
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: iG_PzAf12RTl/icon
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: DWjeGrfvxONg/icon
import uxDesignPngOYEhLcOlWlQq from "./images/uxDesignPng.png"; // plasmic-import: oYEhLcOLWlQq/picture
import brushPngJOpd3OLzUIkc from "./images/brushPng.png"; // plasmic-import: jOPD3oLzUIkc/picture
import programmingPng2EZf9Lywz7K from "./images/programmingPng.png"; // plasmic-import: 2e_zf9Lywz7K/picture
import abstractBackgroundJpgOHuFz6NJvHaT from "./images/abstractBackgroundJpg.jpg"; // plasmic-import: oHuFZ6nJvHaT/picture
import abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorJpg0PgXdoc5Fpmd from "./images/abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorJpg.jpg"; // plasmic-import: 0pgXdoc5Fpmd/picture
import blueAndOrangeAbstractBackgroundFreeVectorJpgZcffLl6J4BnU from "./images/blueAndOrangeAbstractBackgroundFreeVectorJpg.jpg"; // plasmic-import: ZcffLL6J4bnU/picture
import studentGa473640711280JpgTSYyZIhyjg from "./images/studentGa473640711280Jpg.jpg"; // plasmic-import: tSYy_zIHYJG_/picture
import lukePetersB6JiNerWMz0UnsplashJpgB4JtYFzrV29 from "./images/lukePetersB6JiNerWMz0UnsplashJpg.jpg"; // plasmic-import: b4jtYFzr-V29/picture
import benKoldeBs2Ba7T69MMUnsplashJpg0Earc9IGpTed from "./images/benKoldeBs2Ba7T69MMUnsplashJpg.jpg"; // plasmic-import: 0Earc9iGpTed/picture
import danielKorpaiAUmq852V7IUnsplashJpgWtiIvCT3Imz from "./images/danielKorpaiAUmq852V7IUnsplashJpg.jpg"; // plasmic-import: WTIIvC_t3IMZ/picture
import alexSuprunZHvM3XioHoEUnsplashJpgOOvBWQxesR from "./images/alexSuprunZHvM3XioHoEUnsplashJpg.jpg"; // plasmic-import: oOvB_wQXES-R/picture
import christopherCampbellRDeoVtE7VOsUnsplashJpgWdi1DjWk1I2X from "./images/christopherCampbellRDeoVtE7VOsUnsplashJpg.jpg"; // plasmic-import: Wdi1DJWk1I2x/picture
import courtneyCookTsZo17R3M0SUnsplashJpgFZKab97Z68Ir from "./images/courtneyCookTsZo17R3M0SUnsplashJpg.jpg"; // plasmic-import: fZKab97z68ir/picture
import alexanderHippIEebWgY6LAUnsplashJpgF5UnT3Fgl0F from "./images/alexanderHippIEebWgY6LAUnsplashJpg.jpg"; // plasmic-import: f5UnT3FGL0_F/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsl9TsMn1DF1V()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
          />

          <Stack__
            as={"section"}
            data-plasmic-name={"intro"}
            data-plasmic-override={overrides.intro}
            hasGap={true}
            className={classNames(projectcss.all, sty.intro)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__fZtUh)}>
              <div
                data-plasmic-name={"mainTextContainer"}
                data-plasmic-override={overrides.mainTextContainer}
                className={classNames(projectcss.all, sty.mainTextContainer)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Hey there, Anna here \ud83d\udc4b"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sGbxk
                  )}
                >
                  {"Web designer and product designer for hire."}
                </div>
              </div>
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                href={"#about"}
                platform={"react"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jpTdt
                  )}
                >
                  {"About me"}
                </div>
                <RightArrowIcon
                  className={classNames(projectcss.all, sty.svg__eiOst)}
                  role={"img"}
                />
              </PlasmicLink__>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"services"}
            data-plasmic-override={overrides.services}
            hasGap={true}
            className={classNames(projectcss.all, sty.services)}
            id={"Services"}
          >
            <div className={classNames(projectcss.all, sty.freeBox___9Ntav)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aRctx
                )}
                id={"services"}
              >
                {"Services"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__gC7K1
                )}
              >
                {"Embracing constraints to push the boundaries."}
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___2LlsO)}
            >
              <div className={classNames(projectcss.all, sty.column__rcuHp)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__sen1X)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: uxDesignPngOYEhLcOlWlQq,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__db5Hd
                  )}
                >
                  {"UX/UI & Web \nDesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uelVc
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__bQjHl)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__cZeHv)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: brushPngJOpd3OLzUIkc,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__beLPj
                  )}
                >
                  {"Branding & visual \ndesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__q5Emj
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___9YwZo)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__flD8W)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: programmingPng2EZf9Lywz7K,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__gxTuh
                  )}
                >
                  {"Web \ndevelopment"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uRmiD
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"work"}
            data-plasmic-override={overrides.work}
            hasGap={true}
            className={classNames(projectcss.all, sty.work)}
            id={"work"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__ewBd)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kutWd
                )}
                id={"services"}
              >
                {"work"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2___2Az4F
                )}
              >
                {"Privileged to work with on some amazing projects."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__dKcx0)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__iu7NU)}
              >
                <div className={classNames(projectcss.all, sty.column___9XvN)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__muQlc)}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard___7Nkzi
                      )}
                      link={`/project-relaunch`}
                      title={"Project Relaunch"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__vbibu)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__zyhc5)}
                    delay={250}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__odMq0
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: abstractBackgroundJpgOHuFz6NJvHaT,
                        fullWidth: 1920,
                        fullHeight: 1171,
                        aspectRatio: undefined
                      }}
                      link={`/website-redesign`}
                      title={"Website Redesign"}
                    />
                  </Reveal>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__ls5Gr)}
              >
                <div className={classNames(projectcss.all, sty.column__dmBn)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal___94Od)}
                    delay={500}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__cWjDc
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorJpg0PgXdoc5Fpmd,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                      link={`/premium-sass-design`}
                      title={"Premium Saas Design"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__iribO)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__jxW6V)}
                    delay={750}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__et6Hj
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: blueAndOrangeAbstractBackgroundFreeVectorJpgZcffLl6J4BnU,
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                      link={`/web-visual-design`}
                      title={"Web Visual Graphic Design"}
                    />
                  </Reveal>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"about"}
            data-plasmic-override={overrides.about}
            hasGap={true}
            className={classNames(projectcss.all, sty.about)}
            id={"about"}
          >
            <div className={classNames(projectcss.all, sty.freeBox___49WyD)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___0V0CN
                )}
                id={"about"}
              >
                {"About Me"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__u6QLt)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__z8Gp
                )}
              >
                {"Bridging design and no-code."}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9Yxm4
                )}
              >
                {
                  "Anna is an award winning, web designer specialising in no-code solutions. With over 8 years of professional experience I've helped countless startups launch & grow their business."
                }
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__bCsWj)}>
              <div className={classNames(projectcss.all, sty.freeBox__oWgsS)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zsEx6)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5Bqhr)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "311px"
                        : "312px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    loading={"lazy"}
                    src={{
                      src: studentGa473640711280JpgTSYyZIhyjg,
                      fullWidth: 1280,
                      fullHeight: 853,
                      aspectRatio: undefined
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___7BA0K)}
                    displayHeight={"312px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: lukePetersB6JiNerWMz0UnsplashJpgB4JtYFzrV29,
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__yKbU)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mVVb)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: benKoldeBs2Ba7T69MMUnsplashJpg0Earc9IGpTed,
                    fullWidth: 1920,
                    fullHeight: 2449,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__nlh1)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lQ0DQ)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: danielKorpaiAUmq852V7IUnsplashJpgWtiIvCT3Imz,
                    fullWidth: 1920,
                    fullHeight: 2400,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___4K33U)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1Wer
                )}
              >
                {"TESTIMONIALS"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__aiJkQ
                )}
              >
                {"Hear from the folks I've worked with."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox___8MElf)}>
              <div className={classNames(projectcss.all, sty.freeBox__m3SCs)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__odQt6)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__cGgDh)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5Lxng
                      )}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___4DV)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__vpNp)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__ctCkn)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__iY1Tw)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___0By1R)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___2YmRp
                      )}
                    >
                      {"Very experienced"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zxIn
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__mAf0X)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mu0SV
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__fsBk)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: alexSuprunZHvM3XioHoEUnsplashJpgOOvBWQxesR,
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dXrbH
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nZcQv
                          )}
                        >
                          {"Albert David"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mmh3L
                          )}
                        >
                          {"Marketing Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lU7Z0)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__w42Tw)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__ub2Gl)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__f7HD)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__vRaif)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__lxYjm)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__nkuGj)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__xgUmf
                      )}
                    >
                      {"Very fast & skillful"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xpQdc
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__qw28Q)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__gx29G
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__xnu8D)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: christopherCampbellRDeoVtE7VOsUnsplashJpgWdi1DjWk1I2X,
                            fullWidth: 640,
                            fullHeight: 427,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__dg7HW
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___11Bkb
                          )}
                        >
                          {"Arolina"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vWkUc
                          )}
                        >
                          {"Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__o2OzS)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__fWgJx)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__xo38B)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__e4X33)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__gaCt4)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__rh7Fx)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___25BlZ)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__je84S)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___7Oyz4)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___1JkWd
                      )}
                    >
                      {"skilled communicator"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ylKju
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__vi4Bb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mMt60
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__bvpH)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: courtneyCookTsZo17R3M0SUnsplashJpgFZKab97Z68Ir,
                            fullWidth: 640,
                            fullHeight: 960,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__wn3Vr
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__f6Gfx
                          )}
                        >
                          {"Firmona"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wwQte
                          )}
                        >
                          {"Founder, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__svGZy)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yuj4J)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__lGux7)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__qtdnO)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__am99V)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__pmgH2)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___9YFDb)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__nOqcB
                      )}
                    >
                      {"Great design skills"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hCxFf
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__g9880)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__cqWhv
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__niLWb)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: alexanderHippIEebWgY6LAUnsplashJpgF5UnT3Fgl0F,
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column___8Zr4I
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9MNhl
                          )}
                        >
                          {"Motherson"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__txxcL
                          )}
                        >
                          {"Design Lead, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
          <ContactSection
            data-plasmic-name={"contactSection"}
            data-plasmic-override={overrides.contactSection}
            className={classNames("__wab_instance", sty.contactSection)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigationBar",
    "intro",
    "mainTextContainer",
    "h1",
    "link",
    "services",
    "work",
    "about",
    "testimonials",
    "contactSection",
    "footer"
  ],

  navigationBar: ["navigationBar"],
  intro: ["intro", "mainTextContainer", "h1", "link"],
  mainTextContainer: ["mainTextContainer", "h1"],
  h1: ["h1"],
  link: ["link"],
  services: ["services"],
  work: ["work"],
  about: ["about"],
  testimonials: ["testimonials"],
  contactSection: ["contactSection"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    intro: makeNodeComponent("intro"),
    mainTextContainer: makeNodeComponent("mainTextContainer"),
    h1: makeNodeComponent("h1"),
    link: makeNodeComponent("link"),
    services: makeNodeComponent("services"),
    work: makeNodeComponent("work"),
    about: makeNodeComponent("about"),
    testimonials: makeNodeComponent("testimonials"),
    contactSection: makeNodeComponent("contactSection"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Anna.Design",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
